[project]
site_url = "https://otuomela.github.io/hpc-env-eff/"
site_name = "HPC Computing Environment"
site_description = "Self-learning materials for CSC supercomputers"
site_author = "CSC – IT Center for Science Ltd."

copyright = """
Copyright &copy; 2020–2026 CSC – IT Center for Science Ltd.
This work is licensed under a
<a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons
Attribution-ShareAlike 4.0 International License</a>.
This project has received funding from the European High-Performance Computing
Joint Undertaking (EuroHPC JU) under grant agreements No 951732 and 101101903.
"""

repo_url = "https://github.com/otuomela/hpc-env-eff/"
repo_name = "otuomela/hpc-env-eff"
edit_uri = "edit/main/docs/"

nav = [
  { "Home" = "index.md" },
  { "Access" = [
    "access/credentials.md",
    "access/ssh.md",
    "access/certificate.md",
    "access/login.md",
  ]},
  { "Linux basics" = [
    "linux-basics/commands.md",
    "linux-basics/file-editing.md"
  ]},
  { "Disk areas" = [
    "disk-areas/main-disk-areas.md",
    "disk-areas/lue.md"
  ]},
  {
    "Modules" = [
    "modules/roihu-modules.md",
    "modules/roihu-biomodules.md"
  ]},
  {
    "Batch queue system and interactive use" = [
    "batch-jobs/serial.md",
    "batch-jobs/parallel.md",
    "batch-jobs/interactive.md",
    "batch-jobs/bio-data.md"
  ]},
  { "Batch job resource usage" = [
    "batch-resources/sacct-seff-tutorial.md",
    "batch-resources/sacct-seff-exercise.md"
  ]},
  { "Allas" = [
    "allas/allas-basics.md",
    "allas/allas-backup.md",
    "allas/allas-bio.md"
  ]},
  { "Working efficiently with data" = [
    "data-io/fastdisks.md",
    "data-io/allas-batch-jobs.md",
    "data-io/local-rclone.md",
    "data-io/local-disks.md"
  ]},
  {
    "Installing own software" = [
    "installing/binary.md",
    "installing/python.md",
    "installing/r.md",
    "installing/c.md",
    "installing/perl.md",
    "installing/java.md",
    "installing/cmake.md",
    ]
  },
  {
    "Containers and Apptainer" = [
    "containers/apptainer-part1.md",
    "containers/apptainer-part2.md",
    "containers/running-installed.md",
    "containers/getting-containers.md",
    "containers/replicating-conda.md",
    "containers/creating-containers.md"
    ]
  },
  {
    "Speeding up jobs" = [
    "workflows/scaling.md",
    "workflows/hyperqueue.md",
    "workflows/snakemake-ht.md",
    "workflows/gaussian-hq.md",
    "workflows/tune-performance.md"
    ]
  }
]

# extra_css = ["stylesheets/extra.css"]
# extra_javascript = ["javascripts/extra.js"]

[project.theme]
# variant = "classic"
# custom_dir = "overrides"
# favicon = "images/favicon.png"
language = "en"
features = [
  "announce.dismiss",
  # "content.action.edit",
  # "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  # "header.autohide",
  # "navigation.expand",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  # "navigation.instant.progress",
  "navigation.path",
  # "navigation.prune",
  "navigation.sections",
  # "navigation.tabs",
  # "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  # "toc.follow",
  # "toc.integrate",
]

# logo = "assets/logo.png"

# [project.theme.icon]
# logo = "lucide/smile"

# [project.theme.font]
# text = "Inter"
# code = "Jetbrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

# [[project.extra.social]]
# icon = "fontawesome/brands/github"
# link = "https://github.com/user/repo"

# [[project.extra.social]]
# icon = "fontawesome/brands/mastodon"
# link = "https://fosstodon.org/@user"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc.permalink = true
pymdownx.arithmatex.generic = true
pymdownx.betterem = {}
pymdownx.caret = {}
pymdownx.details = {}
pymdownx.emoji.emoji_generator = "zensical.extensions.emoji.to_svg"
pymdownx.emoji.emoji_index = "zensical.extensions.emoji.twemoji"
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.line_spans = "__span"
pymdownx.highlight.pygments_lang_class = true
pymdownx.inlinehilite = {}
pymdownx.keys = {}
pymdownx.magiclink = {}
pymdownx.mark = {}
pymdownx.smartsymbols = {}
# pymdownx.snippets.base_path = "includes"
pymdownx.superfences.custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
pymdownx.tabbed.alternate_style = true
pymdownx.tabbed.combine_header_slug = true
pymdownx.tasklist.custom_checkbox = true
pymdownx.tilde = {}
